projects:
  dev-f1-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: nod5a4hn3vaprmy7fdtopzjni4
        maxDepth: 3
extensions:
  amplify:
    version: 3
