/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
    // aws_project_region: "us-east-1",
    graphqlEndpoint: "https://snzxkwwgyjhbvgkb63ysvj4q24.appsync-api.us-west-2.amazonaws.com/graphql",
    region: "us-west-2",
    authenticationType: "AWS_IAM"
};
