AWSTemplateFormatVersion: "2010-09-09"
Description: Prod S3 Buckets
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: prod
Resources:
  staticAssetsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-anika-f1-app-static'
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: "s3:ObjectCreated:*"
          Function: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${EnvironmentName}-cache-setter-lambda
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET]
          AllowedOrigins: ['*']
          Id: CORSRule1
Outputs:
  staticAssetsS3Bucket:
    Value: !Ref 'staticAssetsS3Bucket'
    Description: S3 static asset bucket.
    Export:
      Name: !Join ['-', [!Ref EnvironmentName, anika, f1app, static]]
